
name: Node.js CI  # CI + CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Inspect Buildx
        run: docker buildx inspect --bootstrap

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            banupriya29/node-ci-cd:${{ github.sha }}
            banupriya29/node-ci-cd:latest

  deploy:
    needs: test
    runs-on: self-hosted

    steps:
      - name: Check runner
        run: |
          echo "CD job is running on the self-hosted runner"
          hostname
          docker --version
          docker info
          kubectl version --client

      - name: Deploy to Kubernetes
        run: |
          kubectl -n node-ci-cd set image deployment/node-ci-cd \
            node-ci-cd=banupriya29/node-ci-cd:${{ github.sha }}

      - name: Verify Kubernetes rollout
        run: |
          kubectl -n node-ci-cd rollout status deployment/node-ci-cd --timeout=120s

      - name: Verify Kubernetes deployment
        run: |
          kubectl -n node-ci-cd get deployment
          kubectl -n node-ci-cd get pods
          kubectl -n node-ci-cd get service

      - name: Health Check
        run: |
          sleep 10
          curl --fail http://103.17.193.35:30000
